name: MultiXscale-compile_lammps
run-name: Compile new Plugin OBMD
on:
  push:
    paths:
      - '.github/**'
      - 'src/OBMD/**'
      - 'examples/OBMD/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: eessi/github-action-eessi@v3
    - name: set up EasyBuild
      run: |
        module load EasyBuild/4.9.4
        module load EESSI-extend/2023.06-easybuild
        export EASYBUILD_TRACE=1
        eb --show-config
    - name: Get EasyConfig
      run: |
        echo $PWD
        wget https://raw.githubusercontent.com/EESSI/dev.eessi.io-example/refs/heads/main/easyconfigs/LAMMPS_OBMD-foss-2023a-software-commit.eb
        ls
        eb LAMMPS_OBMD-foss-2023a-software-commit.eb --software-commit ${{ github.sha }} -x
