name: MultiXscale-trailing-whitespace-actions
run-name: Check new plugins of LAMMPS
on:
  push:
    paths:
      - '.github/**'
      - 'src/OBMD/**'
      - 'examples/OBMD/**'
jobs:
  Get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell 
          filters: |
            changed:
              - 'src/OBMD/**'
              - 'examples/OBMD/**'
      - if: steps.changes.outputs.src == 'true'
        run: echo ${{ steps.changes.outputs.changed_files }}

  
    
  
