name: MultiXscale-generate_lammps_patch
run-name: Generate a patch for the OBMD plugin
on:
  push:
    paths:
      - '.github/**'
      - 'src/OBMD/**'
      - 'examples/OBMD/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
          repository: multixscale/dev.eessi.io-lammps-plugin-obmd
          path: multixscale_dev
          ref: update_patch
    - uses: actions/checkout@v4
      with: 
        repository: lammps/lammps
        path: lammps_upstream
        # This commit needs to be updated when developping on top of another commit of lammps!
        ref: 27e8d0f19cfd60ff513828af74d07d2c8f3c4451
    - uses: actions/checkout@v4
      with:
        path: lammps_dev
    - name: Generate patch file
      continue-on-error: true
      run: |
        pwd
        echo check pr branch
        ls lammps_dev/src/OBMD
        cat lammps_dev/src/version.h
        echo check upstream branch
        cat lammps_upstream/src/version.h
        # make patch file
        diff -ruN --exclude .* lammps_upstream lammps_dev > LAMMPS-2Aug2023_lammps_obmd_package.patch
    - name: Check if patch file was generated
      run: |
        ls LAMMPS-2Aug2023_lammps_obmd_package.patch
        cat LAMMPS-2Aug2023_lammps_obmd_package.patch
    - name: Push patch to MultiXscale/dev.eessi.io-lammps-plugin-obmd
      run: |
        cd multixscale_dev
        git branch
        cp ../LAMMPS-2Aug2023_lammps_obmd_package.patch patches/.
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add patches/LAMMPS-2Aug2023_lammps_obmd_package.patch
        git commit -a -m "update patch"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        repository: multixscale/dev.eessi.io-lammps-plugin-obmd
        directory: multixscale_dev
        branch: update_patch
