name: MultiXscale-compile_lammps
run-name: Compile new Plugin OBMD
on:
  push:
    paths:
      - '.github/**'
      - 'src/OBMD/**'
      - 'examples/OBMD/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        repository: lammps/lammps
        path: lammps_upstream
        # This commit needs to be updated when developping on top of another commit of lammps! 
        # by setting a new value here https://github.com/laraPPr/lammps/settings/variables/actions. 
        ref: ${{ env.LAMMPS_COMMIT }}
    - uses: actions/checkout@v4
      with:
        path: lammps_dev
    - name: Generate patch file
      continue-on-error: true
      run: |
        # make patch file
        diff -ruN --exclude .* lammps_upstream lammps_dev > LAMMPS-2Aug2023_lammps_obmd_package.patch
    - name: Check if patch file was generated
      run: |
        ls LAMMPS-2Aug2023_lammps_obmd_package.patch
        cat LAMMPS-2Aug2023_lammps_obmd_package.patch
    - uses: actions/checkout@v4
      with: 
        repository: multixscale/dev.eessi.io-lammps-plugin-obmd
        path: multixscale_dev
    - uses: eessi/github-action-eessi@v3
    - name: set up EasyBuild
      run: |
        pwd
        mkdir -p multixscale_dev/easyconfigs/l/LAMMPS && cp LAMMPS-2Aug2023_lammps_obmd_package.patch multixscale_dev/easyconfigs/l/LAMMPS/.
        module load EESSI-extend/2023.06-easybuild
        eb --show-config
        echo ${{ github.sha }}
        echo "Get EasyConfig"
        eb multixscale_dev/easyconfigs/LAMMPS_OBMD-foss-2023a-software-commit.eb --software-commit ${{ env.LAMMPS_COMMIT }} --include-easyblocks-from-commit 3725813434972232adde2d84c882801fae629ddf
        module avail LAMMPS
        module load LAMMPS/${{ github.sha }}-foss-2023a-kokkos-dev_OBMD
        echo $EBROOTLAMMPS
        ls $EBROOTLAMMPS
        mpirun -np 4 --oversubscribe lmp -in $EBROOTLAMMPS/examples/OBMD/in.OBMD
