name: MultiXscale-dev-actions
run-name: Check LAMMPS in EESSI
on: [push]
jobs:
  check-LAMMPS-version-EESSI:
    runs-on: ubuntu-latest
    steps:
      - uses: eessi/github-action-eessi@v3
      - name: Test LAMMPS
        run: |
          module avail LAMMPS
        shell: bash
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
