name: MultiXscale-generate_lammps_patch
run-name: Generate a patch for the OBMD plugin
on:
  push:
    paths:
      - '.github/**'
      - 'src/OBMD/**'
      - 'examples/OBMD/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate patch file
      run: |
        pwd
        git remote add lammps https://github.com/laraPPr/lammps
        git remote -v
        git branch
        ls src/OBMD
        # This commit needs to be updated when developping on top of another commit of lammps!
        git checkout 27e8d0f19cfd60ff513828af74d07d2c8f3c4451 # upstream commit of lammps 2Aug2023_update2
        git checkout -b upstream_lammps
        git -a branch
        ls src/OBMD
        git checkout ${{ github.ref_name }}
        ls src/OBMD
        echo $HOME
        
