name: MultiXscale-compile_lammps
run-name: Compile LAMMPS
on:
  push:
    paths:
      - '.github/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
      with:
        eessi_stack_version: "2025.06"
    - name: Install LAMMPS
      run: |
        module load EESSI-extend/2025.06-easybuild
        eb --version
        eb --from-commit 0fb7d96f8f1e0b846a6cf1609dbe689646f15ed9 .github/workflows/LAMMPS-22Jul2025-foss-2024a-kokkos_small.eb
